In [1]:
import gym
env = gym.make('CartPole-v1')
env.reset()
for step_index in range(1000):
    env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    print("Step {}:".format(step_index))
    print("action: {}".format(action))
    print("observation: {}".format(observation))
    print("reward: {}".format(reward))
    print("done: {}".format(done))
    print("info: {}".format(info))
    if done:
        break

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don

Step 0:
action: 1
observation: [ 0.00460292  0.14695193  0.01656309 -0.26855177]
reward: 1.0
done: False
info: {}
Step 1:
action: 0
observation: [ 0.00754196 -0.04840244  0.01119205  0.02930892]
reward: 1.0
done: False
info: {}
Step 2:
action: 0
observation: [ 0.00657391 -0.24368308  0.01177823  0.32550195]
reward: 1.0
done: False
info: {}
Step 3:
action: 1
observation: [ 0.00170025 -0.0487308   0.01828827  0.03655651]
reward: 1.0
done: False
info: {}
Step 4:
action: 1
observation: [ 0.00072564  0.14612418  0.0190194  -0.25030065]
reward: 1.0
done: False
info: {}
Step 5:
action: 0
observation: [ 0.00364812 -0.04926413  0.01401339  0.0483202 ]
reward: 1.0
done: False
info: {}
Step 6:
action: 1
observation: [ 0.00266284  0.1456541   0.01497979 -0.23990865]
reward: 1.0
done: False
info: {}
Step 7:
action: 1
observation: [ 0.00557592  0.3405589   0.01018162 -0.5278291 ]
reward: 1.0
done: False
info: {}
Step 8:
action: 0
observation: [ 0.0123871   0.14529519 -0.00037496 -0.23195541]
reward:

In [2]:
import random
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/dtypes.py:35: DeprecationWarning: ml_dtypes.float8_e4m3b11 is deprecated. Use ml_dtypes.float8_e4m3b11fnuz
  from tensorflow.tsl.python.lib.core import pywrap_ml_dtypes


In [3]:
env = gym.make('CartPole-v1')
env.reset()
goal_steps = 500
score_requirement = 60
initial_games = 100000

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [4]:
def model_data_preparation():
    training_data = []
    accepted_scores = []
    for game_index in range(initial_games):
        score = 0
        game_memory = []
        previous_observation = []
        for step_index in range(goal_steps):
            action = random.randrange(0, 2)
            observation, reward, done, info = env.step(action)

            if len(previous_observation) > 0:
                game_memory.append([previous_observation, action])

            previous_observation = observation
            score += reward
            if done:
                break

        if score >= score_requirement:
            accepted_scores.append(score)
            for data in game_memory:
                if data[1] == 1:
                    output = [0, 1]
                elif data[1] == 0:
                    output = [1, 0]
                training_data.append([data[0], output])

        env.reset()

    print(accepted_scores)

    return training_data

In [5]:
training_data = model_data_preparation()

[79.0, 64.0, 65.0, 62.0, 62.0, 63.0, 64.0, 80.0, 92.0, 60.0, 65.0, 65.0, 67.0, 63.0, 64.0, 70.0, 77.0, 75.0, 61.0, 82.0, 75.0, 77.0, 83.0, 62.0, 82.0, 66.0, 62.0, 63.0, 64.0, 60.0, 64.0, 75.0, 62.0, 64.0, 73.0, 69.0, 77.0, 68.0, 63.0, 75.0, 64.0, 75.0, 76.0, 71.0, 61.0, 75.0, 63.0, 64.0, 67.0, 66.0, 68.0, 60.0, 60.0, 67.0, 62.0, 70.0, 68.0, 70.0, 60.0, 63.0, 77.0, 85.0, 68.0, 62.0, 64.0, 77.0, 61.0, 66.0, 76.0, 68.0, 62.0, 68.0, 77.0, 61.0, 62.0, 77.0, 62.0, 68.0, 60.0, 61.0, 72.0, 60.0, 85.0, 77.0, 77.0, 67.0, 86.0, 68.0, 65.0, 60.0, 69.0, 68.0, 73.0, 62.0, 62.0, 95.0, 76.0, 67.0, 60.0, 71.0, 66.0, 60.0, 68.0, 64.0, 66.0, 66.0, 60.0, 66.0, 65.0, 89.0, 60.0, 78.0, 60.0, 71.0, 75.0, 62.0, 65.0, 69.0, 63.0, 73.0, 66.0, 61.0, 68.0, 71.0, 66.0, 61.0, 71.0, 70.0, 60.0, 81.0, 62.0, 88.0, 83.0, 61.0, 67.0, 77.0, 86.0, 100.0, 67.0, 65.0, 62.0, 78.0, 62.0, 67.0, 66.0, 67.0, 75.0, 74.0, 73.0, 71.0, 67.0, 74.0, 61.0, 61.0, 60.0, 82.0, 78.0, 63.0, 60.0, 90.0, 64.0, 75.0, 78.0, 69.0, 72.0, 68.0, 62

In [6]:
def build_model(input_size, output_size):
    model = Sequential()
    model.add(Dense(128, input_dim=input_size, activation='relu'))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(output_size, activation='linear'))
    model.compile(loss='mse', optimizer=Adam())

    return model

In [7]:
def train_model(training_data):
    X = np.array([i[0] for i in training_data]).reshape(-1, len(training_data[0][0]))
    y = np.array([i[1] for i in training_data]).reshape(-1, len(training_data[0][1]))
    print(X)
    print(y)
    model = build_model(input_size=len(X[0]), output_size=len(y[0]))

    model.fit(X, y, epochs=10)
    return model

In [8]:
trained_model = train_model(training_data)

[[-0.01904887  0.17226763  0.04437019 -0.32525244]
 [-0.01560352  0.36673066  0.03786515 -0.60361934]
 [-0.00826891  0.56130314  0.02579276 -0.8841392 ]
 ...
 [ 0.579045    0.60123    -0.19601159 -0.27962694]
 [ 0.5910696   0.40936536 -0.20160413 -0.05460002]
 [ 0.59925693  0.6067213  -0.20269611 -0.40350917]]
[[0 1]
 [0 1]
 [1 0]
 ...
 [1 0]
 [0 1]
 [1 0]]
Epoch 1/10
3482/3482 [==============================] - 8s 2ms/step - loss: 0.2345
Epoch 2/10
3482/3482 [==============================] - 6s 2ms/step - loss: 0.2312
Epoch 3/10
3482/3482 [==============================] - 7s 2ms/step - loss: 0.2306
Epoch 4/10
3482/3482 [==============================] - 6s 2ms/step - loss: 0.2301
Epoch 5/10
3482/3482 [==============================] - 7s 2ms/step - loss: 0.2300
Epoch 6/10
3482/3482 [==============================] - 6s 2ms/step - loss: 0.2298
Epoch 7/10
3482/3482 [==============================] - 7s 2ms/step - loss: 0.2298
Epoch 8/10
3482/3482 [==============================] - 6s 

In [9]:
scores = []
choices = []
for each_game in range(100):
    score = 0
    prev_obs = []
    for step_index in range(goal_steps):
        env.render()
        if len(prev_obs)==0:
            action = random.randrange(0,2)
        else:
            action = np.argmax(trained_model.predict(prev_obs.reshape(-1, len(prev_obs)))[0])

        choices.append(action)
        new_observation, reward, done, info = env.step(action)
        prev_obs = new_observation
        score+=reward
        if done:
            break

    env.reset()
    scores.append(score)

print(scores)
print('Average Score:',sum(scores)/len(scores))
print('choice 1:{}  choice 0:{}'.format(choices.count(1)/len(choices),choices.count(0)/len(choices)))

/usr/local/lib/python3.10/dist-packages/gym/core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(


Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 29ms/step
[101.0, 290.0, 500.0, 105.0, 500.0, 500.0, 500.0, 500.0, 116.0, 118.0, 500.0, 500.0, 500.0, 308.0, 500.0, 107.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 351.0, 500.0, 252.0, 500.0, 500.0, 227.0, 500.0, 387.0, 293.0, 335.0, 500.0, 353.0, 322.0, 437.0, 252.0, 500.0, 242.0, 228.0, 300.0, 342.0, 500.0, 371.0, 283.0, 251.0, 219.0, 240.0, 500.0, 500.0, 500.0, 500.0, 500.0, 261.0, 500.0, 444.0, 383.0, 306.0, 500.0, 379.0, 500.0, 500.0, 500.0, 500.0, 248.0, 271.0, 121.0, 500.0, 399.0, 500.0, 500.0, 360.0, 235.0, 251.0, 253.0, 500.0, 101.0, 500.0, 500.0, 230.0, 500.0, 234.0, 500.0, 500.0, 221.0, 237.0, 245.0, 500.0, 500.0, 500.0, 281.0, 363.0, 500.0, 500.0, 291.0, 249.0, 379.0, 500.0, 99.0]
Average Score: 381.71
choice 1:0.5051740850383799  choice 0:0.4948259149616201
